apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ej-code-s2i
  labels:
    app: ej-code-s2i-app
spec:
  lookupPolicy:
    local: false
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ej-code-s2i
  labels:
    app: ej-code-s2i-app
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/danielopezh/os.git"
      ref: main
    contextDir: ""
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: "python:3.12-ubi9"
  output:
    to:
      kind: ImageStreamTag
      name: "ej-code-s2i:latest"
